### ISSUE TITLE
ActiveRecord Videos Feedback

### ISSUE THREAD

**Issue by infopro94** [learn-co-curriculum/activerecord-associations-video-review-blog-cli-with-activerecord-and-associations#4]
After sitting through all four videos (gah) I have a suggestion:

There is so much redundancy in these lessons that it should be possible to edit them down to four 30-minute or two 60-minute segments. That would be far kinder than the four hours that students currently have to slog through.

There's a lot of good information here, it's just not presented efficiently.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions.

Generally speaking, the videos are meant as material to augment the written curriculum and should be viewed as optional. After hearing feedback from students wanting more videos we have placed a few throughout the course. Because every student learns differently though, these videos are simply another way to deepen your understanding. If it doesn't work for you that's no problem. To better communicate this we will add a disclaimer explaining all of this to the lessons containing video resources. The written curriculum will independently cover all the required knowledge. Of course, we will continue to improve the videos and written material.

If, after reviewing the written curriculum, you still feel that there is a gap, feel free to reopen the issue.

As always, thanks for contributing! 💙
